appurl: "http://bozaro.vercel.app"
items:
  -
    id: FejlYgRVsAAbKxY
    word: だいじょうぶ
    image: https://pbs.twimg.com/media/FejlYgRVsAAbKxY.jpg
    src: pic.twitter.com/YMYv8PYbX6
  -
    id: FejnL6DUcAEKWLz
    word: すみません
    image: https://pbs.twimg.com/media/FejnL6DUcAEKWLz.jpg
    src: pic.twitter.com/LfpCuQtsC0
  -
    id: Fh73MLfVIAA39Mo
    word: ねつれつかんげい
    image: https://pbs.twimg.com/media/Fh73MLfVIAA39Mo.jpg
    src: pic.twitter.com/wWtGlgpMva
  -
    id: Fh732gwVEAASJou
    word: どんびき
    image: https://pbs.twimg.com/media/Fh732gwVEAASJou.jpg
    src: pic.twitter.com/RGATfrDpWT
  -
    id: Fh74QjBUAAA8O61
    word: ろっく
    image: https://pbs.twimg.com/media/Fh74QjBUAAA8O61.jpg
    src: pic.twitter.com/lMpaRgpDgx
  -
    id: Fh75Bx2UUAINh5b
    word: とらうま
    image: https://pbs.twimg.com/media/Fh75Bx2UUAINh5b.jpg
    src: pic.twitter.com/0Ejn4PRipa
  -
    id: Fh75Tk3UoAE5yFK
    word: とらうま
    image: https://pbs.twimg.com/media/Fh75Tk3UoAE5yFK.jpg
    src: pic.twitter.com/GBc8emLf1X
  -
    id: Fh77GMCVIAAQCIQ
    word: かわいい
    image: https://pbs.twimg.com/media/Fh77GMCVIAAQCIQ.jpg
    src: pic.twitter.com/gB1A2IvyoY
  -
    id: Fif6EzaUYAA7TaZ
    word: もりあげる
    image: https://pbs.twimg.com/media/Fif6EzaUYAA7TaZ.jpg
    src: pic.twitter.com/QfX1NH6bGl
  -
    id: Fif6zUOUcAAzQfN
    word: がんばろう
    image: https://pbs.twimg.com/media/Fif6zUOUcAAzQfN.jpg
    src: pic.twitter.com/bWD7bnP3TO
  -
    id: Fif8KnIUoAAvFyi
    word: よくやった
    image: https://pbs.twimg.com/media/Fif8KnIUoAAvFyi.jpg
    src: pic.twitter.com/sHwcZXifQO
  -
    id: Fif9Fl-UAAckbJJ
    word: じゅもん
    image: https://pbs.twimg.com/media/Fif9Fl-UAAckbJJ.jpg
    src: pic.twitter.com/XFXVtncvmE
  -
    id: Fif9dIkVQAAny3a
    word: じんせい
    image: https://pbs.twimg.com/media/Fif9dIkVQAAny3a.jpg
    src: pic.twitter.com/PN1vsg5gNR
  -
    id: Fif9qfOUUAAIo1h
    word: ほっさ
    image: https://pbs.twimg.com/media/Fif9qfOUUAAIo1h.jpg
    src: pic.twitter.com/IQJOqUFXEt
  -
    id: FkppBCCaUAAqSiv
    word: ぎんが
    image: https://pbs.twimg.com/media/FkppBCCaUAAqSiv.jpg
    src: pic.twitter.com/PlkZY6UxR5
  -
    id: FjD-TY7VIAERG0k
    word: おわかれ
    image: https://pbs.twimg.com/media/FjD-TY7VIAERG0k.jpg
    src: pic.twitter.com/MP6IeUOZUU
  -
    id: FjD_YyxUoAYXl1W
    word: あたまからっぽ
    image: https://pbs.twimg.com/media/FjD_YyxUoAYXl1W.jpg
    src: pic.twitter.com/Ie1vZ7cJtj
  -
    id: FjD_w71VQAEIBtT
    word: ばくはつしさん
    image: https://pbs.twimg.com/media/FjD_w71VQAEIBtT.jpg
    src: pic.twitter.com/XM7sxyzn3h
  -
    id: FjEABJJUoAA6a1c
    word: おつかれさま
    image: https://pbs.twimg.com/media/FjEABJJUoAA6a1c.jpg
    src: pic.twitter.com/sLVBITPCSD
  -
    id: FjEBfB_VQAAYk1b
    word: とんび
    image: https://pbs.twimg.com/media/FjEBfB_VQAAYk1b.jpg
    src: pic.twitter.com/l0ZK36kDpi
  -
    id: FkLv5QSUEAEbBTa
    word: ねてた
    image: https://pbs.twimg.com/media/FkLv5QSUEAEbBTa.jpg
    src: pic.twitter.com/iHEcwZEzu3
  -
    id: FjoAN93UoAAGbK6
    word: めいど
    image: https://pbs.twimg.com/media/FjoAN93UoAAGbK6.jpg
    src: pic.twitter.com/YeX8hPD6Tz
  -
    id: FjoCKAMUYAEwknc
    word: だめだー
    image: https://pbs.twimg.com/media/FjoCKAMUYAEwknc.jpg
    src: pic.twitter.com/Iq2oouvgwN
  -
    id: FjoEAQeVUAAgKiw
    word: うでぐみ
    image: https://pbs.twimg.com/media/FjoEAQeVUAAgKiw.jpg
    src: pic.twitter.com/KeGuJclacb
  -
    id: FjoEaLmUoAAxqqe
    word: かっこいい
    image: https://pbs.twimg.com/media/FjoEaLmUoAAxqqe.jpg
    src: pic.twitter.com/ms1jaIZpUS
  -
    id: FkG6zGcUcAAqx26
    word: はやすぎ
    image: https://pbs.twimg.com/media/FkG6zGcUcAAqx26.jpg
    src: pic.twitter.com/LQg6pBRWFh
  -
    id: FkMDeLuVsAAbrvh
    word: はかせ
    image: https://pbs.twimg.com/media/FkMDeLuVsAAbrvh.jpg
    src: pic.twitter.com/H94fVwY6D1
  -
    id: FkMDsHiVUAIRXrG
    word: げんじつとうひ
    image: https://pbs.twimg.com/media/FkMDsHiVUAIRXrG.jpg
    src: pic.twitter.com/7GG3yMDVVj
  -
    id: FkMDyPTUAAALkzY
    word: いばしょ
    image: https://pbs.twimg.com/media/FkMDyPTUAAALkzY.jpg
    src: pic.twitter.com/629FLWug8b
  -
    id: FkMFJuhVUAE8tNC
    word: きぜつ
    image: https://pbs.twimg.com/media/FkMFJuhVUAE8tNC.jpg
    src: pic.twitter.com/K8UwUiCwX2
  -
    id: FkMFiYdVEAAaYX-
    word: みわく
    image: https://pbs.twimg.com/media/FkMFiYdVEAAaYX-.jpg
    src: pic.twitter.com/1Ck2JufRtG
  -
    id: FkMFx7jUYAIBLnO
    word: じゅもん
    image: https://pbs.twimg.com/media/FkMFx7jUYAIBLnO.jpg
    src: pic.twitter.com/M9NLxdsVcH
  -
    id: FkMHPWQVsAASm2I
    word: あいそわらい
    image: https://pbs.twimg.com/media/FkMHPWQVsAASm2I.jpg
    src: pic.twitter.com/LQv4wEgkx3
  -
    id: FkMIDFtVEAAmd3t
    word: きんちょう
    image: https://pbs.twimg.com/media/FkMIDFtVEAAmd3t.jpg
    src: pic.twitter.com/iEnwqq3g0e
  -
    id: FkwHeiIakAEFil4
    word: ふぁんになる
    image: https://pbs.twimg.com/media/FkwHeiIakAEFil4.jpg
    src: pic.twitter.com/DH5YRKi9fx
  -
    id: FkwIbyOacAMvQ85
    word: よけろ
    image: https://pbs.twimg.com/media/FkwIbyOacAMvQ85.jpg
    src: pic.twitter.com/IQ17Zsyp2g
  -
    id: FkwJQs4acAA6edy
    word: ごめんなさい
    image: https://pbs.twimg.com/media/FkwJQs4acAA6edy.jpg
    src: pic.twitter.com/GZRCXxoXkA
  -
    id: FkwJdJBaYAEDeGJ
    word: ゆきち
    image: https://pbs.twimg.com/media/FkwJdJBaYAEDeGJ.jpg
    src: pic.twitter.com/jbJ2G10kgj
  -
    id: FkwJ0BoaUAA52PF
    word: ばいとやめよう
    image: https://pbs.twimg.com/media/FkwJ0BoaUAA52PF.jpg
    src: pic.twitter.com/iJs6LNgP3G
